//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proiect_C_.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.5.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MzF2ORknrQTynfUaS6fZjEId9Eel7DqRluS66jYA5gA=")]
        public string SmtpAddress {
            get {
                return ((string)(this["SmtpAddress"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("xjpY4MevzVMeqFqNVLQeNQ==")]
        public string SmtpPort {
            get {
                return ((string)(this["SmtpPort"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("tQlU4b0Q8Dm1aDYk/iUbREUnbN35RGGwijFgJE2bVyMarCARWaCghlvzY4Bh7yef")]
        public string Email {
            get {
                return ((string)(this["Email"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("acbDwS3nJckvtd4I8iNVqQ==")]
        public string Password {
            get {
                return ((string)(this["Password"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AA2KYt8Izaw)PsH7jFssI7C.!FupQskv(+MuYdxFTmFMY)ZYhB+bWIfuFfr5xY9951/mXpxN#Rav7jnlZ" +
            "QD2rYxT05t3LSVhySKd1pYOM0hA57*furxV5v?BLIDFGFm5")]
        public string Salt {
            get {
                return ((string)(this["Salt"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("b0bZ0tUZQ3Porm4zXtMp+N0GzlOuaMgTlYClhwvTLYocrBTdkYRCQkUYVggNP3agAbvMKaM31sysT1MMi" +
            "mUaGQ==")]
        public string DbConnection {
            get {
                return ((string)(this["DbConnection"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("OAz/N7v6Tvf/LRKD0nmaW4xpHo2YwJlm/Ek+d35ttJK68i+fLQ/FXDj/ZxusGjog")]
        public string TwilioSID {
            get {
                return ((string)(this["TwilioSID"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("pIbXWZmvRyjuTpC3rC2zFIhDItcIc6tmcQIatPbgvE4m+SHxxSXe3ZDMfisch4R0")]
        public string TwilioAuthToken {
            get {
                return ((string)(this["TwilioAuthToken"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6xYQlhQJoqHgw1LPzaKbkQ==")]
        public string PhoneNumber {
            get {
                return ((string)(this["PhoneNumber"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("y5TnSORBOih1Mw0frWgvAOF1VmIIW+8VsmT0TbINJyRCj6gW4pa7GQ3ID0564HIZ5Yc4IkNLtF/SLKgJ1" +
            "b50GIE5xCic/2gMgUAt37FmQa9DlsChPsES3Y2hs2jsfbhVZ0Dsedr4kkCQxGsTaQK64ZcT1my8envZw" +
            "P6a8WtmpeeJaNxaHbMZOUUD+Atb5LP9hu++lEzB1DsFG7kh3SkRDKm0auUBZu02WXAmFOapruw=")]
        public string OldDbConnection {
            get {
                return ((string)(this["OldDbConnection"]));
            }
        }
    }
}
